name: API Tests

on:
    push:
        branches: "*"

jobs:
    build:
        runs-on: ubuntu-latest

        services:
            # Label used to access the service container
            postgres:
                # Docker Hub image
                image: postgres
                # Provide the password for postgres
                env:
                    POSTGRES_PASSWORD: postgres
                # Set health checks to wait until postgres has started
                options: >-
                    --health-cmd pg_isready
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5
                ports:
                    - 5432:5432

        strategy:
            matrix:
                node-version: [12.x]

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install PostgreSQL 10 Client
              run: sudo apt-get -yqq install libpq-dev

            - name: Install pnpm
              run: npm i -g pnpm

            - name: Config pnpm
              run: pnpm config set verify-store-integrity false

            - name: Cache node_modules
              uses: actions/cache@v1
              with:
                  path: ~/.pnpm-store
                  key: ${{ hashFiles('pnpm-lock.yaml') }}

            - name: Install dependencies
              run: pnpm i

            - name: Test with pnpm
              run: pnpm run test
              env:
                # The hostname used to communicate with the PostgreSQL service container
                POSTGRES_HOST: localhost
                # The default PostgreSQL port
                POSTGRES_PORT: 5432
